# Practical 7 
## AIM : To perform PCA on Iris datadet and find the first 2 principle components 

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns

In [13]:
df = sns.load_dataset('iris')

In [14]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [15]:
features = df.drop(columns="species")
feature_names = ["sepalLength", "sepal_width", "petal_length", "petal_width"]
features.columns = feature_names
print("Selected feature columns: ", feature_names)

Selected feature columns:  ['sepalLength', 'sepal_width', 'petal_length', 'petal_width']


In [16]:
mean_vec = np.mean(features, axis=0)
std_vec = np.std(features, axis=0)
standardized_features = (features - mean_vec) / std_vec
standardized_features

sepalLength  sepal_width  petal_length  petal_width
0      -0.900681     1.019004     -1.340227    -1.315444
1      -1.143017    -0.131979     -1.340227    -1.315444
2      -1.385353     0.328414     -1.397064    -1.315444
3      -1.506521     0.098217     -1.283389    -1.315444
4      -1.021849     1.249201     -1.340227    -1.315444
..           ...          ...           ...          ...
145     1.038005    -0.131979      0.819596     1.448832
146     0.553333    -1.282963      0.705921     0.922303
147     0.795669    -0.131979      0.819596     1.053935
148     0.432165     0.788808      0.933271     1.448832
149     0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [17]:
cov_matrix = np.cov(standardized_features, rowvar=False)
cov_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [18]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print(f"Eigenvalues{eigenvalues} \neigenvectors{eigenvectors}")

Eigenvalues[2.93808505 0.9201649  0.14774182 0.02085386] 
eigenvectors[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [19]:
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

In [20]:
num_components = 2
selected_eigenvectors = eigenvectors_sorted[:, :num_components]

In [21]:
pca_result = np.dot(standardized_features, selected_eigenvectors)

pca_df = pd.DataFrame(pca_result, columns=["PC1", "PC2"])
pca_df

PC1       PC2
0   -2.264703 -0.480027
1   -2.080961  0.674134
2   -2.364229  0.341908
3   -2.299384  0.597395
4   -2.389842 -0.646835
..        ...       ...
145  1.870503 -0.386966
146  1.564580  0.896687
147  1.521170 -0.269069
148  1.372788 -1.011254
149  0.960656  0.024332

[150 rows x 2 columns]