In [64]:
import numpy as np
import pandas as pd

In [65]:
print(np.__version__, pd.__version__)

2.2.1 2.2.3


In [66]:
print('\n numpy methods\n')


 numpy methods



In [67]:
np.array([1,2,3])

array([1, 2, 3])

In [68]:
np.zeros(3)

array([0., 0., 0.])

In [69]:
np.ones(3)

array([1., 1., 1.])

In [70]:
np.arange(1,4)

array([1, 2, 3])

In [71]:
np.linspace(1.0 ,5.0 ,num = 3)

array([1., 3., 5.])

In [72]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [73]:
np.reshape(a,4)

array([1, 2, 3, 4])

In [74]:
b = np.array([[1,2],[3,4]])
print(f"b ={b}")
print("\n")
c = np.transpose(b)
print(f"c={c}")

b =[[1 2]
 [3 4]]


c=[[1 3]
 [2 4]]


In [75]:
d = np.dot(a, b)
d

array([[ 7, 10],
       [15, 22]])

In [76]:
np.sum(a)

np.int64(10)

In [77]:
np.mean(b)

np.float64(2.5)

In [78]:
e = np.array([15,72,83,26,38])
np.std(e)

np.float64(26.331729908990027)

In [79]:
np.max(e)

np.int64(83)

In [80]:
np.min(e)

np.int64(15)

In [81]:
f = np.array([[14,67,37],[24,62,89]])
print(np.argmax(f,axis = 0))
print(np.argmax(f,axis = 1))

[1 0 1]
[1 2]


In [82]:
print(np.argmin(f,axis = 0))
print(np.argmin(f,axis = 1))

[0 1 0]
[0 0]


In [83]:
x = np.random.rand(2,2,3)
print(np.shape(x))
x

(2, 2, 3)


array([[[0.69470987, 0.25688631, 0.04739953],
        [0.61612204, 0.30217168, 0.91946981]],

       [[0.32559943, 0.31796312, 0.44175404],
        [0.05015795, 0.45711299, 0.56355396]]])

In [84]:
y = np.random.randn(2,2,2)
print(np.shape(y))
y

(2, 2, 2)


array([[[-0.18937843,  0.39499996],
        [-0.77224271,  0.44312596]],

       [[ 0.22994369,  0.33807772],
        [ 2.29581982, -0.72624242]]])

In [85]:
B = np.random.randint(0, 16272, 8)
B

array([ 1936,   266, 15216,   161,  6536,  2143,  3473, 14862],
      dtype=int32)

In [86]:
np.ones_like(B)

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [87]:
np.zeros_like(B)

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [88]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
j = np.diag(B)
j

array([[ 1936,     0,     0,     0,     0,     0,     0,     0],
       [    0,   266,     0,     0,     0,     0,     0,     0],
       [    0,     0, 15216,     0,     0,     0,     0,     0],
       [    0,     0,     0,   161,     0,     0,     0,     0],
       [    0,     0,     0,     0,  6536,     0,     0,     0],
       [    0,     0,     0,     0,     0,  2143,     0,     0],
       [    0,     0,     0,     0,     0,     0,  3473,     0],
       [    0,     0,     0,     0,     0,     0,     0, 14862]],
      dtype=int32)

In [92]:
temp_1 = np.array([1,2,3,4])
temp_2 = np.array([5,6,7,8])

f = np.concatenate((temp_1,temp_2), axis=0)
f

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
g = np.split(f,2,axis=0)
g

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [98]:
np.random.choice(11,8,replace = False)

array([5, 2, 3, 0, 4, 8, 9, 6], dtype=int32)