In [1]:
import numpy as np
import pandas as pd

In [2]:
print(np.__version__, pd.__version__)

2.2.2 2.2.3


# Numpy methods

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.arange(1,4)

array([1, 2, 3])

In [7]:
np.linspace(1.0 ,5.0 ,num = 3)

array([1., 3., 5.])

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
np.reshape(a,4)

array([1, 2, 3, 4])

In [10]:
b = np.array([[1,2],[3,4]])
print(f"b ={b}")
print("\n")
c = np.transpose(b)
print(f"c={c}")

b =[[1 2]
 [3 4]]


c=[[1 3]
 [2 4]]


In [11]:
d = np.dot(a, b)
d

array([[ 7, 10],
       [15, 22]])

In [12]:
np.sum(a)

np.int64(10)

In [13]:
np.mean(b)

np.float64(2.5)

In [14]:
e = np.array([15,72,83,26,38])
np.std(e)

np.float64(26.331729908990027)

In [15]:
np.max(e)

np.int64(83)

In [16]:
np.min(e)

np.int64(15)

In [17]:
f = np.array([[14,67,37],[24,62,89]])
print(np.argmax(f,axis = 0))
print(np.argmax(f,axis = 1))

[1 0 1]
[1 2]


In [18]:
print(np.argmin(f,axis = 0))
print(np.argmin(f,axis = 1))

[0 1 0]
[0 0]


In [19]:
x = np.random.rand(2,2,3)
print(np.shape(x))
x

(2, 2, 3)


array([[[0.03893639, 0.90003119, 0.23016904],
        [0.34546206, 0.10954128, 0.29737898]],

       [[0.7939329 , 0.68819212, 0.81892107],
        [0.18304819, 0.51239772, 0.38450335]]])

In [20]:
y = np.random.randn(2,2,2)
print(np.shape(y))
y

(2, 2, 2)


array([[[-0.32383819,  0.19248649],
        [-1.48383925,  0.62552034]],

       [[-0.5023233 , -1.62669921],
        [-0.75692254, -0.3665472 ]]])

In [21]:
B = np.random.randint(0, 16272, 8)
B

array([  815,  8258, 14548,  9963, 10846,  6713,   627, 10128],
      dtype=int32)

In [22]:
np.ones_like(B)

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [23]:
np.zeros_like(B)

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [24]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
j = np.diag(B)
j

array([[  815,     0,     0,     0,     0,     0,     0,     0],
       [    0,  8258,     0,     0,     0,     0,     0,     0],
       [    0,     0, 14548,     0,     0,     0,     0,     0],
       [    0,     0,     0,  9963,     0,     0,     0,     0],
       [    0,     0,     0,     0, 10846,     0,     0,     0],
       [    0,     0,     0,     0,     0,  6713,     0,     0],
       [    0,     0,     0,     0,     0,     0,   627,     0],
       [    0,     0,     0,     0,     0,     0,     0, 10128]],
      dtype=int32)

In [26]:
temp_1 = np.array([1,2,3,4])
temp_2 = np.array([5,6,7,8])

f = np.concatenate((temp_1,temp_2), axis=0)
f

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
g = np.split(f,2,axis=0)
g

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [28]:
np.random.choice(11,8,replace = False)

array([6, 4, 1, 3, 7, 9, 8, 0], dtype=int32)

In [29]:
np.where(f < 6,f ,5*f)

array([ 1,  2,  3,  4,  5, 30, 35, 40])

In [30]:
np.unique([1,2,1,4,3,5,2,3],return_counts=False)

array([1, 2, 3, 4, 5])

In [31]:
A = np.array([1,2,3,])
B = np.array([4,5,6])

In [32]:
np.vstack((A,B))

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6])

In [34]:
C = np.array([[10, 20], [30, 40]])
np.linalg.inv(C)

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

# Pandas Methods 

In [35]:
series = pd.Series([1, 2, 3,4 ,5 ,6])
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [36]:
data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data)
df

A  B
0  1  3
1  2  4

In [37]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.head(2)

A  B
0  1  4
1  2  5

In [38]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.tail(2)

A  B
1  2  5
2  3  6

In [39]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


In [40]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.describe()

A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

In [41]:
df.shape

(3, 2)

In [42]:
df.drop('A',axis=1)

B
0  4
1  5
2  6

In [43]:
df.rename(columns={'B': 'A'})

A  A
0  1  4
1  2  5
2  3  6

In [44]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
df.isnull()

A      B
0  False  False
1   True  False
2  False   True

In [45]:
df.notnull()

A      B
0   True   True
1  False   True
2   True  False

In [46]:
df.fillna(2)

A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  2.0

In [47]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
df.dropna()

A    B
0  1.0  4.0

In [48]:
df = pd.DataFrame({'A': [1, 1, 2], 'B': [3, 4, 5]})
grouped = df.groupby('A').sum()
grouped

B
A   
1  7
2  5

In [49]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [1, 2], 'C': [5, 6]})
merged = pd.merge(df1, df2, on='A')
merged

A  B  C
0  1  3  5
1  2  4  6

In [50]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
concatenated = pd.concat([df1, df2])
concatenated

A
0  1
1  2
0  3
1  4

In [51]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': ['X', 'X', 'Y']})
pivot = df.pivot_table(values='B', index='C', aggfunc='sum')
pivot

B
C   
X  9
Y  6

In [52]:
df

A  B  C
0  1  4  X
1  2  5  X
2  3  6  Y

In [53]:
df.apply(lambda x: x * 2)

A   B   C
0  2   8  XX
1  4  10  XX
2  6  12  YY

In [54]:
df.iloc[1]

A    2
B    5
C    X
Name: 1, dtype: object

In [55]:
df.loc[1,'A']

np.int64(2)

In [56]:
df = pd.DataFrame({'A': [3, 1, 2], 'B': [6, 5, 4]})
df.sort_values(by='A')

A  B
1  1  5
2  2  4
0  3  6

In [57]:
df.sort_index()

A  B
0  3  6
1  1  5
2  2  4

In [58]:
df.corr()

A    B
A  1.0  0.5
B  0.5  1.0

In [59]:
df.cumsum()

A   B
0  3   6
1  4  11
2  6  15

In [60]:
df.value_counts()

A  B
1  5    1
2  4    1
3  6    1
Name: count, dtype: int64

In [61]:
df = pd.Series(['apple', 'banana', 'cherry'])
df.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [62]:
df = pd.DataFrame({'A': [1, 2,3,4,5,6,7,8,9,10, ], 'B': [10, 20,30,40,50,60,70,80,90,100]})
df.to_csv('output.csv')

In [63]:
df = pd.DataFrame({'A': [1, 2,3,4,5,6,7,8,9,10, ], 'B': [10, 20,30,40,50,60,70,80,90,100]})
df.to_excel('output.xlsx')

In [64]:
df = pd.DataFrame({'A': [1, 2,3,4,5,6,7,8,9,10, ], 'B': [10, 20,30,40,50,60,70,80,90,100]})
df.to_json('output.xlsx')